comment: false

codecov:
  token: 304dedae-7987-4bff-937d-efaf193df25b

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
